vich_uploader:
    metadata:
        type: attribute
    db_driver: orm
    
    mappings:
        article_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

 
           